name: Dr Richard Huysmans
favicon: null
layout_spectrum: 0.08985986327752471
typography_spectrum: 0.49229
title: Dr Richard Huysmans
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#4abcfa'
    - '#fefefe'
    - '#919191'
    - '#44636e'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
