typography_spectrum: 0.13584
color:
  brandColors:
    - '#0279b3'
    - '#ffffff'
    - '#505656'
    - '#b1b4b4'
    - '#7b8080'
  brandStrength: 0.8125
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.13776
analytics:
  google: null
  facebook: null
  twitter: null
name: Dr Richard Huysmans
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Dr Richard Huysmans
description: Helping researchers be commercially smart
purpose: []
