title: Dr Richard Huysmans
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5
  brandStrength: 0.8125
  lightness: 1
  brandColors:
    - '#0279b3'
    - '#ffffff'
    - '#505656'
    - '#b1b4b4'
    - '#7b8080'
  rhythmicContrast: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Dr Richard Huysmans
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.13584
layout_spectrum: 0.13776
