name: Dr Richard Huysmans
favicon: null
layout_spectrum: 0.50193
typography_spectrum: 0.13584
title: Dr Richard Huysmans
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0279b3'
    - '#ffffff'
    - '#505656'
    - '#b1b4b4'
    - '#7b8080'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
