name: Dr Richard Huysmans
favicon: null
layout_spectrum: 0.25915
typography_spectrum: 0.10886
title: Dr Richard Huysmans
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#aed7ed'
    - '#32a5db'
    - '#231f20'
    - '#7e7c7d'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
