name: Dr Richard Huysmans
favicon: null
layout_spectrum: 0.08985986327752471
typography_spectrum: 0.49229
title: Dr Richard Huysmans
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5e5e66'
    - '#242426'
    - '#86858d'
    - '#babdc4'
    - '#e19572'
  brandStrength: 0.2549296780489385
  lightness: 0.37814518250525
  saturation: 0.88379549770616
  rhythmicContrast: 0.5829664482735097
purpose: []
