title: Dr Richard Huysmans
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5537634
  brandStrength: 1
  lightness: 0.5089605
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#378BBE'
    - '#5F5F5F'
    - '#1F1F1F'
  rhythmicContrast: 0.5322581
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Dr Richard Huysmans
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.13584
layout_spectrum: 0.7240143
